import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

const fornSans = GeistSans;

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fornSans.className} scroll-smooth`}>{children}</body>
    </html>
  );
}
